build:
  cuda_version: "12.1.1"
  python_packages:
    - "torch==2.3.0"
    - "transformers==4.40.2"
    - "openpyxl==3.1.5"
    - "accelerate==0.31.0"
    - "peft==0.10.0"
    - "bitsandbytes==0.43.1"
    - "pandas==2.2.2"
    - "numpy==1.26.4"
    - "scipy==1.14.0"
